apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: question4
spec:
  containers:
    - name: c1
      image: busybox:1.31.1
      command: ["sh", "-c", "while true; do date >> /vol/date.log; sleep 5; done"]
      volumeMounts:
        - name: vol
          mountPath: /vol
    - name: c2
      image: busybox:1.31.1
      command: ["tail", "-f", "/vol/date.log"]
      volumeMounts:
        - name: vol
          mountPath: /vol
  volumes:
    - name: vol
      emptyDir: {}
