apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: web
spec:
  containers:
    - name: pod1-container
      image: httpd:2.4.41-alpine
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
